#!/bin/bash
#MSUB -V -j oe
#MSUB -l partition=rzmerl
#MSUB -l nodes=1
#MSUB -l walltime=12:00:00
#MSUB -A bdivp


STUDY="mpi-node-strong"

NITER=10

# Run Kripke Test Problem 2
KP=KP2
ZONES=12,12,12
DLIST=1:12,2:6,4:3,6:2,12:1
GLIST=1:256,2:128,4:64,8:32,16:16,32:8,64:4,128:2,256:1
LEGEXP=4

srun  -n1 ./kripke  --procs 1,1,1 --out ${STUDY}_${HOSTNAME}_${KP}_1.out  --zones 12,12,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n2 ./kripke  --procs 2,1,1 --out ${STUDY}_${HOSTNAME}_${KP}_2.out  --zones 12,12,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n4 ./kripke  --procs 2,2,1 --out ${STUDY}_${HOSTNAME}_${KP}_4.out  --zones 12,12,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n8 ./kripke  --procs 2,2,2 --out ${STUDY}_${HOSTNAME}_${KP}_8.out  --zones 12,12,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n16 ./kripke --procs 4,2,2 --out ${STUDY}_${HOSTNAME}_${KP}_16.out --zones 12,12,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}



