#!/bin/bash
#MSUB -V -j oe
#MSUB -l partition=rzmerl
#MSUB -l nodes=1
#MSUB -l walltime=12:00:00
#MSUB -A bdivp


STUDY="mpi-node-weak"

NITER=10

# Run Kripke Test Problem 0
KP=KP0
ZONES=12,12,12
DLIST=1:12,2:6,4:3,6:2,12:1
GLIST=1:64,2:32,4:16,8:8,16:4,32:2,64:1
LEGEXP=4

srun  -n1 ./kripke  --procs 1,1,1 --out ${STUDY}_${HOSTNAME}_${KP}_1.out  --zones 12,12,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n2 ./kripke  --procs 2,1,1 --out ${STUDY}_${HOSTNAME}_${KP}_2.out  --zones 24,12,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n4 ./kripke  --procs 2,2,1 --out ${STUDY}_${HOSTNAME}_${KP}_4.out  --zones 24,24,12 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n8 ./kripke  --procs 2,2,2 --out ${STUDY}_${HOSTNAME}_${KP}_8.out  --zones 24,24,24 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}
srun  -n16 ./kripke --procs 4,2,2 --out ${STUDY}_${HOSTNAME}_${KP}_16.out --zones 48,24,24 --niter $NITER --dir $DLIST --grp $GLIST --legendre ${LEGEXP}



